# Generated by Django 3.2.8 on 2021-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211116_1638'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_version',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='cart_product', to='core.ProductVersion', verbose_name='Product Version'),
        ),
    ]
