# Generated by Django 3.2.8 on 2021-11-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211120_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Onlayn kart ilə ödəmə ', 'Cart'), ('Qapıda nağd ödəmə', 'Cash')], max_length=6000),
        ),
    ]
