# Generated by Django 3.2.8 on 2021-11-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211115_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='color',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_version', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
