# Generated by Django 3.2.8 on 2021-11-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211116_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='storage',
            field=models.CharField(max_length=100),
        ),
    ]
