# Generated by Django 3.2.8 on 2021-10-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Minimum age'),
            preserve_default=False,
        ),
    ]
